
import "./globals.css";
import Navbar from "@/components/Views/Navbar";
import Wrapper from "@/components/Views/Wrapper";
import Footer from "@/components/Views/Footer";
import { Playfair_Display } from 'next/font/google'; // Ensure this import is correct and matches your setup
import { Metadata } from "next";

const playFairDisplay_inter = Playfair_Display({ subsets: ["latin"], variable: '--font-playfairdisplay' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={playFairDisplay_inter.variable}>

        <Navbar />
        <Wrapper>
          {children}
        </Wrapper>
        <Footer />
      </body>
    </html>
  );
}

// initialUser={null}